# Generated by Django 4.1.7 on 2023-04-12 23:09

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TourList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tourlist_title", models.CharField(blank=True, max_length=155)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "tourlist_photo",
                    models.ImageField(blank=True, upload_to="photos/%Y/%m/%d"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "created_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
