# Generated by Django 4.1.7 on 2023-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
