# Generated by Django 4.1.7 on 2023-04-20 03:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_tour_day_10_title_tour_day_11_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="tour_included_2",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
